export const navigations = [
  { name: 'Dashboard', path: '/dashboard/default', icon: 'dashboard' },
  // { label: 'PAGES', type: 'label' },
  // {
  //   name: 'Session/Auth',
  //   icon: 'security',
  //   children: [
  //     { name: 'Sign in', iconText: 'SI', path: '/session/signin' },
  //     // { name: 'Sign up', iconText: 'SU', path: '/session/signup' },
  //     { name: 'Forgot Password', iconText: 'FP', path: '/session/forgot-password' },
  //     { name: 'Error', iconText: '404', path: '/session/404' },
  //   ],
  // },
  { label: 'Components', type: 'label' },
  {
    name: 'Components',
    icon: 'favorite',
    children: [
      { name: 'Query Form', path: '/query/form', iconText: 'A' },
      { name: 'Display MasterMind', path: '/display/mastermind', iconText: 'B' },
      { name: 'Display Banner', path: '/display/banner', iconText: 'C' },
      { name: 'Display Nextians', path: '/display/nextians', iconText: 'D' },
      { name: 'Nextians Details', path: '/nextians/details', iconText: 'E' },
      { name: 'Master Mind Details', path: '/display/mind', iconText: 'F' },
      { name: 'Success Stories', path: '/success/stories', iconText: 'I' },
      { name: 'Blogs', path: '/display/blog', iconText: 'M' },
      { name: 'Video Snippts', path: '/video/snippts', iconText: 'R' },
      { name: 'Offfer Query', path: '/offers/query', iconText: 'S' },
      { name: 'All FAQ', path: '/all/faq', iconText: 'S' },
      { name: 'Exams', path: '/all/exams', iconText: 'S' },
      { name: 'Table', path: '/material/table', iconText: 'T' },
    ],
  },
  { label: 'Pages', type: 'label' },
  {
    name: 'All Courses',
    icon: 'books',
    children: [
      { name: 'Course List', path: '/courses/list', iconText: 'E' },
      { name: 'Courses', path: '/courses', iconText: 'F' },
      // { name: 'PlanC', path: '/courses/plan-c', iconText: 'G' },
      // { name: 'PlanZero', path: '/courses/plan-zero', iconText: 'H' },
      // { name: 'PlanNP', path: '/courses/plan-np', iconText: 'I' },
      // { name: 'PlanUG', path: '/courses/plan-ug', iconText: 'J' },
      // { name: 'PlanMSC', path: '/courses/plan-msc', iconText: 'K' },
      // { name: 'PlanRRR', path: '/courses/plan-rrr', iconText: 'L' },
      // { name: 'PlanTH', path: '/courses/plan-th', iconText: 'M' },
    ],
  },
  // {
  //   name: 'Inner Courses',
  //   icon: 'security',
  //   children: [
  //     { name: 'Inner PlanA', path: '/inner/courses/plan-a', iconText: 'E' },
  //     { name: 'Inner PlanB', path: '/inner/courses/plan-b', iconText: 'F' },
  //     { name: 'Inner Planc', path: '/inner/courses/plan-c', iconText: 'F' },
  //     { name: 'Inner PlanZero', path: '/inner/courses/plan-zero', iconText: 'F' },
  //     { name: 'Inner PlanNP', path: '/inner/courses/plan-np', iconText: 'F' },
  //     { name: 'Inner PlanUG', path: '/inner/courses/plan-ug', iconText: 'F' },
  //     { name: 'Inner PlanMSC', path: '/inner/courses/plan-msc', iconText: 'F' },
  //     { name: 'Inner PlanRRR', path: '/inner/courses/plan-rrr', iconText: 'F' },
  //     { name: 'Inner PlanTH', path: '/inner/courses/plan-th', iconText: 'F' },
  //   ],
  // },
];
